# Generated by Django 3.1a1 on 2020-05-18 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('cedula', models.DecimalField(decimal_places=0, max_digits=12)),
                ('fecha_nacimiento', models.DateField()),
                ('frecha_registro', models.DateField()),
                ('conectado', models.BooleanField()),
                ('oximetria', models.DecimalField(decimal_places=0, max_digits=3)),
                ('frecuenciaCardiaca', models.DecimalField(decimal_places=0, max_digits=3)),
                ('pletismografia', models.JSONField()),
                ('valoresValidos', models.BooleanField()),
                ('numeroPicos', models.DecimalField(decimal_places=0, max_digits=3)),
                ('balanceIRRDC', models.DecimalField(decimal_places=0, max_digits=3)),
                ('fiO2', models.DecimalField(decimal_places=0, max_digits=3)),
                ('pip', models.DecimalField(decimal_places=0, max_digits=3)),
                ('vt', models.DecimalField(decimal_places=0, max_digits=3)),
                ('frecuenciaRespitatoria', models.DecimalField(decimal_places=0, max_digits=3)),
                ('presion', models.JSONField()),
                ('volumen', models.JSONField()),
                ('flujo', models.JSONField()),
            ],
        ),
    ]
