# Generated by Django 6.0 on 2026-06-16 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_esterilizadores', '0002_alter_usuario_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Esterilizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=20)),
                ('serie', models.CharField(max_length=20)),
                ('volumen', models.CharField(max_length=20)),
                ('registro_sanitario', models.DateField()),
                ('conectado', models.BooleanField()),
                ('temperatura_actual', models.DecimalField(decimal_places=0, max_digits=3)),
                ('temperatua', models.JSONField()),
                ('presion_actual', models.DecimalField(decimal_places=0, max_digits=3)),
                ('presion', models.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name='usuario',
        ),
    ]
