# Generated by Django 6.0 on 2026-06-16 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_esterilizadores', '0003_esterilizador_delete_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esterilizador',
            name='registro_sanitario',
            field=models.CharField(max_length=20),
        ),
    ]
