# Generated by Django 6.0 on 2026-06-16 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_esterilizadores', '0004_alter_esterilizador_registro_sanitario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='esterilizador',
            old_name='temperatua',
            new_name='temperatura',
        ),
    ]
